"use client";

import { useState } from "react";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  ShadingType,
} from "docx";

interface ExportButtonsProps {
  text: string;
  filename?: string;
}

function triggerDownload(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}

function formatDateLong(d: Date) {
  return d.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
}

export default function ExportButtons({
  text,
  filename = "transcript",
}: ExportButtonsProps) {
  const [exportingDocx, setExportingDocx] = useState(false);

  // ── TXT ────────────────────────────────────────────────────────────────────
  const exportTxt = () => {
    const date = formatDateLong(new Date());
    const header = [
      `Transcription — ${date}`,
      `Language: Czech`,
      `${"─".repeat(48)}`,
      "",
    ].join("\n");

    const blob = new Blob([header + text], { type: "text/plain;charset=utf-8" });
    triggerDownload(blob, `${filename}.txt`);
  };

  // ── DOCX ───────────────────────────────────────────────────────────────────
  const exportDocx = async () => {
    setExportingDocx(true);
    try {
      const date = formatDateLong(new Date());
      const FONT = "Calibri";

      const doc = new Document({
        // Embed font info so Word knows Calibri is intended
        styles: {
          default: {
            document: {
              run: { font: FONT, size: 24 }, // 12 pt baseline
            },
          },
        },

        sections: [
          {
            properties: {
              page: {
                margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 }, // 1 in margins
              },
            },
            children: [
              // ── Title ───────────────────────────────────────────────────
              new Paragraph({
                heading: HeadingLevel.TITLE,
                alignment: AlignmentType.LEFT,
                spacing: { after: 120 },
                children: [
                  new TextRun({
                    text: `Transcription — ${date}`,
                    font: FONT,
                    size: 36,      // 18 pt
                    bold: true,
                    color: "1F1F1F",
                  }),
                ],
              }),

              // ── Metadata line ────────────────────────────────────────────
              new Paragraph({
                alignment: AlignmentType.LEFT,
                spacing: { after: 360 },
                shading: { type: ShadingType.SOLID, color: "F3F0FF" },
                border: {
                  left: { style: BorderStyle.SINGLE, size: 12, color: "7C3AED" },
                },
                children: [
                  new TextRun({
                    text: "  Language: ",
                    font: FONT,
                    size: 20,      // 10 pt
                    bold: true,
                    color: "5B21B6",
                  }),
                  new TextRun({
                    text: "Czech (cs)",
                    font: FONT,
                    size: 20,
                    color: "5B21B6",
                  }),
                  new TextRun({
                    text: "     Model: ",
                    font: FONT,
                    size: 20,
                    bold: true,
                    color: "5B21B6",
                  }),
                  new TextRun({
                    text: "onnx-community/whisper-large-v3-turbo",
                    font: FONT,
                    size: 20,
                    color: "5B21B6",
                  }),
                  new TextRun({
                    text: "     Generated by AI",
                    font: FONT,
                    size: 20,
                    italics: true,
                    color: "7C3AED",
                  }),
                ],
              }),

              // ── Body text ────────────────────────────────────────────────
              // Split on newlines so paragraph spacing is preserved
              ...text.split("\n").map(
                (line) =>
                  new Paragraph({
                    alignment: AlignmentType.JUSTIFIED,
                    spacing: { line: 360, after: 0 }, // 1.5× line spacing
                    children: [
                      new TextRun({
                        text: line || " ",
                        font: FONT,
                        size: 24,  // 12 pt
                        color: "1F1F1F",
                      }),
                    ],
                  })
              ),
            ],
          },
        ],
      });

      const blob = await Packer.toBlob(doc);
      triggerDownload(blob, `${filename}.docx`);
    } finally {
      setExportingDocx(false);
    }
  };

  // ── UI ─────────────────────────────────────────────────────────────────────
  return (
    <div className="flex items-center gap-2">
      {/* TXT */}
      <button
        onClick={exportTxt}
        title="Export as plain text"
        className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium
          bg-gray-800 hover:bg-gray-700 text-gray-300 hover:text-white
          transition-colors border border-gray-700"
      >
        <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round"
            d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0
              0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m.75 12l3 3m0
              0l3-3m-3 3v-6m-1.5-9H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0
              .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504
              1.125-1.125V11.25a9 9 0 00-9-9z" />
        </svg>
        .txt
      </button>

      {/* DOCX */}
      <button
        onClick={exportDocx}
        disabled={exportingDocx}
        title="Export as Word document"
        className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium
          bg-gray-800 hover:bg-gray-700 text-gray-300 hover:text-white
          transition-colors border border-gray-700
          disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {exportingDocx ? (
          <span className="w-3.5 h-3.5 rounded-full border-2 border-gray-400 border-t-transparent animate-spin" />
        ) : (
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round"
              d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125
                0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m.75 12l3
                3m0 0l3-3m-3 3v-6m-1.5-9H5.625c-.621 0-1.125.504-1.125
                1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0
                1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
          </svg>
        )}
        .docx
      </button>
    </div>
  );
}
