"use client";

import { useState } from "react";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  ShadingType,
} from "docx";

interface ExportButtonsProps {
  text: string;
  /** Base filename without extension (e.g. "lecture-01"). */
  filename?: string;
  /** Original audio duration in seconds — shown in the DOCX metadata block. */
  durationSeconds?: number;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function triggerDownload(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}

function formatDateLong(d: Date) {
  return d.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
}

function formatDurationHMS(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) return `${h}h ${m}m ${s}s`;
  if (m > 0) return `${m}m ${s}s`;
  return `${s}s`;
}

// ── Component ─────────────────────────────────────────────────────────────────

export default function ExportButtons({
  text,
  filename = "transcript",
  durationSeconds,
}: ExportButtonsProps) {
  const [exportingDocx, setExportingDocx] = useState(false);
  const [copied, setCopied] = useState(false);

  // ── Copy ───────────────────────────────────────────────────────────────────
  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for non-secure contexts
      const ta = document.createElement("textarea");
      ta.value = text;
      ta.style.position = "fixed";
      ta.style.opacity  = "0";
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  // ── TXT ────────────────────────────────────────────────────────────────────
  const exportTxt = () => {
    const date    = formatDateLong(new Date());
    const durLine = durationSeconds ? `Duration: ${formatDurationHMS(durationSeconds)}\n` : "";
    const enhLine = `Enhancement: None\n`;
    const header  = [
      `Lecture Transcription — ${date}`,
      `File: ${filename}`,
      durLine.trimEnd(),
      enhLine.trimEnd(),
      `Language: Czech`,
      "─".repeat(48),
      "",
      "",
    ].filter(Boolean).join("\n");

    const blob = new Blob([header + text], { type: "text/plain;charset=utf-8" });
    triggerDownload(blob, `${filename}.txt`);
  };

  // ── DOCX ───────────────────────────────────────────────────────────────────
  const exportDocx = async () => {
    setExportingDocx(true);
    try {
      const date = formatDateLong(new Date());
      const FONT = "Calibri";

      // Metadata lines for the info block
      const metaLines: string[] = [
        `File: ${filename}`,
        ...(durationSeconds ? [`Duration: ${formatDurationHMS(durationSeconds)}`] : []),
        `Enhancement: None`,
        `Language: Czech (cs-CZ)`,
        `Model: onnx-community/whisper-large-v3-turbo`,
        `Generated by AI`,
      ];

      const doc = new Document({
        // Czech locale — Word activates cs-CZ spellcheck automatically
        styles: {
          default: {
            document: {
              run: {
                font:   FONT,
                size:   24,       // 12 pt baseline
                language: { value: "cs-CZ" },
              },
            },
          },
        },

        sections: [
          {
            properties: {
              page: {
                margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 }, // 1 in
              },
            },
            children: [

              // ── Title ───────────────────────────────────────────────────────
              new Paragraph({
                heading: HeadingLevel.TITLE,
                alignment: AlignmentType.LEFT,
                spacing: { after: 80 },
                children: [
                  new TextRun({
                    text: "Lecture Transcription",
                    font: FONT,
                    size: 40,      // 20 pt
                    bold: true,
                    color: "1F1F1F",
                    language: { value: "cs-CZ" },
                  }),
                ],
              }),

              // ── Date subtitle ───────────────────────────────────────────────
              new Paragraph({
                alignment: AlignmentType.LEFT,
                spacing: { after: 280 },
                children: [
                  new TextRun({
                    text: date,
                    font: FONT,
                    size: 22,      // 11 pt
                    color: "6B7280",
                    language: { value: "cs-CZ" },
                  }),
                ],
              }),

              // ── Metadata block ──────────────────────────────────────────────
              new Paragraph({
                alignment: AlignmentType.LEFT,
                spacing: { before: 0, after: 400 },
                shading: { type: ShadingType.SOLID, color: "F3F0FF" },
                border: {
                  left: { style: BorderStyle.SINGLE, size: 18, color: "7C3AED" },
                },
                children: metaLines.flatMap((line, idx) => [
                  new TextRun({
                    text: `  ${line}`,
                    font: FONT,
                    size: 18,      // 9 pt
                    color: "5B21B6",
                    break: idx === 0 ? 0 : 1,
                    language: { value: "cs-CZ" },
                  }),
                ]),
              }),

              // ── Body text ────────────────────────────────────────────────────
              // Each "\n"-separated line becomes its own paragraph so Word
              // renders Czech paragraph breaks correctly.
              ...text.split("\n").map(
                (line) =>
                  new Paragraph({
                    alignment: AlignmentType.JUSTIFIED,
                    spacing: { line: 360, after: line === "" ? 120 : 0 },
                    children: [
                      new TextRun({
                        text: line || " ",
                        font: FONT,
                        size: 24,  // 12 pt
                        color: "1F1F1F",
                        language: { value: "cs-CZ" },
                      }),
                    ],
                  })
              ),
            ],
          },
        ],
      });

      const blob = await Packer.toBlob(doc);
      triggerDownload(blob, `${filename}.docx`);
    } finally {
      setExportingDocx(false);
    }
  };

  // ── UI ─────────────────────────────────────────────────────────────────────
  return (
    <div className="space-y-3">

      {/* Primary action — Export to Word */}
      <button
        onClick={exportDocx}
        disabled={exportingDocx}
        className="w-full flex items-center justify-center gap-2.5 rounded-xl px-4 py-3
          text-sm font-semibold transition-all
          bg-blue-600 hover:bg-blue-500 active:scale-[0.99] text-white
          shadow-md shadow-blue-900/30
          disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:bg-blue-600"
      >
        {exportingDocx ? (
          <span className="w-4 h-4 rounded-full border-2 border-white border-t-transparent animate-spin" />
        ) : (
          <svg className="w-4 h-4 shrink-0" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round"
              d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0
                0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m.75 12l3 3m0
                0l3-3m-3 3v-6m-1.5-9H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0
                .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504
                1.125-1.125V11.25a9 9 0 00-9-9z" />
          </svg>
        )}
        {exportingDocx ? "Generating Word document…" : "Export to Word (.docx)"}
      </button>

      {/* Secondary row — TXT + Copy */}
      <div className="flex gap-2">
        <button
          onClick={exportTxt}
          className="flex-1 flex items-center justify-center gap-1.5 rounded-xl px-3 py-2
            text-sm font-medium transition-colors
            bg-gray-800 hover:bg-gray-700 border border-gray-700
            text-gray-300 hover:text-white"
        >
          <svg className="w-3.5 h-3.5 shrink-0" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round"
              d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0
                0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m.75 12l3 3m0
                0l3-3m-3 3v-6m-1.5-9H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0
                .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504
                1.125-1.125V11.25a9 9 0 00-9-9z" />
          </svg>
          Export .txt
        </button>

        <button
          onClick={copyToClipboard}
          className={`flex-1 flex items-center justify-center gap-1.5 rounded-xl px-3 py-2
            text-sm font-medium transition-all border
            ${copied
              ? "bg-emerald-500/15 border-emerald-500/40 text-emerald-400"
              : "bg-gray-800 hover:bg-gray-700 border-gray-700 text-gray-300 hover:text-white"
            }`}
        >
          {copied ? (
            <>
              <svg className="w-3.5 h-3.5 shrink-0" fill="none" stroke="currentColor" strokeWidth={2.5} viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
              </svg>
              Copied!
            </>
          ) : (
            <>
              <svg className="w-3.5 h-3.5 shrink-0" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round"
                  d="M15.75 17.25v3.375c0 .621-.504 1.125-1.125 1.125h-9.75a1.125
                    1.125 0 01-1.125-1.125V7.875c0-.621.504-1.125 1.125-1.125H6.75a9.06
                    9.06 0 011.5.124m7.5 10.376h3.375c.621 0 1.125-.504
                    1.125-1.125V11.25c0-4.46-3.243-8.161-7.5-8.876a9.06 9.06 0
                    00-1.5-.124H9.375c-.621 0-1.125.504-1.125 1.125v3.5m7.5
                    10.375H9.375a1.125 1.125 0 01-1.125-1.125v-9.25m12
                    6.625v-1.875a3.375 3.375 0 00-3.375-3.375h-1.5a1.125 1.125 0
                    01-1.125-1.125v-1.5a3.375 3.375 0 00-3.375-3.375H9.75" />
              </svg>
              Copy text
            </>
          )}
        </button>
      </div>
    </div>
  );
}
